### ISSUE TITLE
A lot of connections

### ISSUE THREAD

**Issue by YouROK** [anacrolix/dht#25] opened 2018-09-03 15:36 UTC
With bootstrap and when connecting to the torrent, there are about 1000 connections.
Connections are not replaced, but added, if after bootstrap connect to the torrent, there will be about ~2000 connections, etc.
My ISP blocked me access because it thinks it's a virus attack

Over time, connections are disconnected

**Comment by anacrolix** [comment] 2018-09-03 16:30
Can you identify what revision introduced this? Likely this will be fixed by #24.

**Comment by anacrolix** [comment] 2018-09-04 01:59
@YouROK Thanks for picking up on that, I didn't have the DHT context then that I do now.

**Comment by anacrolix** [comment] 2018-10-22 06:14
Should be fixed by https://github.com/anacrolix/dht/commit/efcc29278754bdd5e766edfb6675f3fe0199fc6f.

**Comment by YouROK** [comment] 2018-10-31 20:55
I updated the dht package
It did not help, I look at the connections on the router(keenetic ultra) and not in the statistics

**Comment by YouROK** [comment] 2018-10-31 20:57
I use the goutp (github.com/anacrolix/utp) package if this helps

**Comment by anacrolix** [comment] 2018-11-02 06:07
Perhaps you could try with utp disabled, DisableUTP in [torrent.ClientConfig](https://godoc.org/github.com/anacrolix/torrent#ClientConfig), and confirm that fixes the issue for you?

**Comment by YouROK** [comment] 2018-11-02 11:46
No, it did not help, dht does not work when utp is disabled

**Comment by anacrolix** [comment] 2018-11-02 11:54
Woops, that's a bug. And I can see the cause for it too.

**Comment by anacrolix** [comment] 2018-11-02 12:08
What client wrapper are you using?

**Comment by YouROK** [comment] 2018-11-02 12:29
TorrServer
https://github.com/YouROK/TorrServer

**Comment by YouROK** [comment] 2018-11-02 12:31
Settings sets in https://github.com/YouROK/TorrServer/blob/1d1316581bc55c3a8a29ac65c917b9df79ede9e3/src/server/torr/BTServer.go#L65

**Comment by anacrolix** [comment] 2018-11-04 06:14
The issue you're now seeing, should be caused by a lack of rate limiting on uTP connections in https://github.com/anacrolix/torrent. Could you try with https://github.com/anacrolix/torrent/commit/c50e59166dd15835d55b1daf65976e616bbc8de1, which adds rate limiting to new connections and should cover the uTP issue?

**Comment by YouROK** [comment] 2018-11-04 10:32
> The issue you're now seeing, should be caused by a lack of rate limiting on uTP connections in https://github.com/anacrolix/torrent. Could you try with [anacrolix/torrent@c50e591](https://github.com/anacrolix/torrent/commit/c50e59166dd15835d55b1daf65976e616bbc8de1), which adds rate limiting to new connections and should cover the uTP issue?
Test it

This is what happens in the statistics of my router after add torrent
[PasteBin](https://paste.ubuntu.com/p/DgDwgcVvfh/)
10.0.0.10 my ip in router
maybe this will help solve the problem

If you need to check something else, tell me I will do everything, otherwise users complain that there is not enough peers

**Comment by YouROK** [comment] 2018-11-04 11:12
When disable utp and enable dht, the router first freeze, but after a while I showed ~500 connections and after a while the connections increased to ~1500, in the client statistics I saw the connection to dht and there were about ~1300 announcements

I assume that dht connected to all the announcers

**Comment by anacrolix** [comment] 2018-11-04 21:02
@YouROK [these](https://github.com/anacrolix/dht/files/2546306/paste.ubuntu.com.txt) statistics are with UTP disabled? What is the meaning of the last column?

**Comment by anacrolix** [comment] 2018-11-05 22:12
Is that the number of bytes in the last packet, the MTU, or the number of pending bytes to be sent?

**Comment by elgatito** [comment] 2018-11-07 18:06
Confirm there are a lot of connections coming out.
`DisableUTP: true`
DHT enabled, UTP disabled.
After starting a torrent - about 8-10k connections on the router, mostly UDP. 

DHT, should not use UDP connections for peers' connections if UDP was disabled in the library?

Do DHT announce only peers with UDP protocol enabled? Or TCP peers also there?

**Comment by anacrolix** [comment] 2018-11-08 01:03
See https://gitter.im/anacrolix/torrent?at=5be389f8bb06d73a993cc703, for some clarifications about connection tracking vs connections.

**Comment by anacrolix** [comment] 2018-11-08 01:05
DHT announce peers regardless of enabled protocols. Addresses obtained from the DHT may support TCP, uTP, or both.

**Comment by elgatito** [comment] 2018-11-08 07:36
@anacrolix maybe optional rate-limit connections in DHT?

**Comment by anacrolix** [comment] 2018-12-21 02:59
This should be fixed by recent commits.

**Closed by anacrolix** 2018-12-21 02:59 UTC
